WebGis_Projeto/GIS_Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('WebGis.urls', namespace='WebGis')),
    path('admin/', admin.site.urls),
]

WebGis_Projeto/WebGis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from WebGis.views import (
    CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView,
    ServicoCreateView, ServicoUpdateView, ServicoDeleteView, ServicoListView,
    RegistroServicoCreateView, RegistroServicoUpdateView, RegistroServicoDeleteView,
    RegistroServicoListView, RegistroServicoDetailView, IndexTemplateView
)

app_name = 'WebGis'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('categoria/', CategoriaListView.as_view(), name='categoria_list'),
    path('categoria/create/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categoria/update/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categoria/delete/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_delete'),
    path('servico/', ServicoListView.as_view(), name='servico_list'),
    path('servico/create/', ServicoCreateView.as_view(), name='servico_create'),
    path('servico/update/<int:pk>/', ServicoUpdateView.as_view(), name='servico_update'),
    path('servico/delete/<int:pk>/', ServicoDeleteView.as_view(), name='servico_delete'),
    path('registro_servico/create/', RegistroServicoCreateView.as_view(), name='registro_servico_create'),
    path('registro_servico/update/<int:pk>/', RegistroServicoUpdateView.as_view(), name='registro_servico_update'),
    path('registro_servico/delete/<int:pk>/', RegistroServicoDeleteView.as_view(), name='registro_servico_delete'),
    path('registro_servico/', RegistroServicoListView.as_view(), name='registro_servico_list'),
    path('registro_servico/detail/<int:pk>/', RegistroServicoDetailView.as_view(), name='registro_servico_detail'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WebGis_Projeto/WebGis/forms.py
from django import forms
from django.db import models
from django.contrib.gis.db import models
from django.contrib.gis import forms
from django.contrib.gis.geos import Point
from leaflet.forms.widgets import LeafletWidget
from WebGis.models import Categoria, Servico, RegistroServico, Campus, User
from django_flatpickr.widgets import DatePickerInput, TimePickerInput, DateTimePickerInput
from django.contrib.gis.db.models import PointField

class CampusForm(forms.ModelForm):
    class Meta:
        model = Campus
        fields = ['nome', 'ponto_central']
        widgets = {
            'ponto': forms.HiddenInput(),
         }
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome', 'descricao']

class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ['categoria', 'nome', 'descricao']

class RegistroServicoForm(forms.ModelForm):
    class Meta:
        model = RegistroServico
        exclude = ('usuario', 'ip_origem')
        widgets = {
            'ponto': forms.HiddenInput(),
            "data_registro": DateTimePickerInput(),
        }
        fields = ['servico', 'campi', 'data_registro', 'descricao', 'ip_origem', 'foto', 'ponto']
        servico = forms.ModelChoiceField(queryset=Servico.objects.all(), required=True)
        campi   = forms.ModelChoiceField(queryset=Campus.objects.all(), required=True)
        data_registro = forms.DateTimeField(required=True, widget=DateTimePickerInput())
        descricao = forms.CharField(required=False, widget=forms.Textarea())
        ip_origem = forms.CharField(required=False, widget=forms.HiddenInput())
        foto    = forms.FileField(required=False, widget=forms.FileField())
        latitude  = forms.DecimalField(required=False, widget=forms.HiddenInput())
        longitude = forms.DecimalField(required=False, widget=forms.HiddenInput())
        endereco =  forms.DecimalField(required=False, widget=forms.HiddenInput())
        ponto = forms.PointField()

WebGis_Projeto/WebGis/views.py
from typing import Any, Dict, Optional
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import models
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ( TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView)
from django.contrib.gis.geos import GEOSGeometry
from geopy.geocoders import Nominatim
from WebGis.forms import ( CategoriaForm, ServicoForm, RegistroServicoForm, CampusForm )
from WebGis.models import ( Categoria, Servico, RegistroServico, Campus, ReporteUsuario, UnidadeGestora)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.gis.geos import Point
import exifread
import requests
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from PIL import Image
from PIL.ExifTags import TAGS

class IndexTemplateView(TemplateView):
  template_name = "WebGis/index.html"

class CategoriaListView(ListView):
    model = Categoria
    template_name = 'WebGis/categoria_list.html'
    context_object_name = 'categorias'
    paginate_by = 10

class CategoriaCreateView(LoginRequiredMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'WebGis/categoria_form.html'
    success_url = reverse_lazy('WebGis:categoria_list')

class CategoriaUpdateView(LoginRequiredMixin, UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'WebGis/categoria_form.html'
    success_url = reverse_lazy('WebGis:categoria_list')

class CategoriaDeleteView(LoginRequiredMixin, DeleteView):
    model = Categoria
    template_name = 'WebGis/categoria_confirm_delete.html'
    success_url = reverse_lazy('WebGis:categoria_list')

class ServicoListView(ListView):
    model = Servico
    paginate_by = 10
    template_name = 'WebGis/servico_list.html'
    context_object_name = 'servicos'

class ServicoCreateView(LoginRequiredMixin, CreateView):
    model = Servico
    form_class = ServicoForm
    template_name = 'WebGis/servico_form.html'
    success_url = reverse_lazy('WebGis:servico_list')
    
class ServicoUpdateView(LoginRequiredMixin, UpdateView):
    model = Servico
    form_class = ServicoForm
    template_name = 'WebGis/servico_form.html'
    success_url = reverse_lazy('WebGis:servico_list')

    def get_object(self, queryset=None):
        servico = None
        # Os campos {pk} e {slug} estão presentes em self.kwargs
        id = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if id is not None:
            # Busca o serviço apartir do id
            servico = Servico.objects.filter(id=id).first()
        elif slug is not None:
            # Pega o campo slug do Model
            campo_slug = self.get_slug_field()
            # Busca o serviço apartir do slug
            servico = Servico.objects.filter(**{campo_slug: slug}).first()
        # Retorna o objeto encontrado
        return servico

class ServicoDeleteView(LoginRequiredMixin, DeleteView):
    model = Servico
    template_name = 'WebGis/servico_confirm_delete.html'
    success_url = reverse_lazy('WebGis:servico_list')


class RegistroServicoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = RegistroServico
    form_class = RegistroServicoForm
    template_name = 'WebGis/registro_servico_form_new.html'
    success_url = reverse_lazy('WebGis:registro_servico_list')
    sucess_message = 'Parabéns !!! Você registrou com sucesso sua Ocorrência.'

    def form_invalid(self, form):
        print("Erro")
        return HttpResponse('Erro')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.instance.ip_origem = self.request.META.get('HTTP_X_REAL_IP')
        #campus = self.Campus.objects.get(nome=form.instance.campi)
        if form.cleaned_data.get('endereco'):
            geolocator = Nominatim(user_agent="my-app")
            location = geolocator.geocode(form.cleaned_data['endereco'])
            if location:
                form.cleaned_data['latitude'] = location.latitude
                form.cleaned_data['longitude'] = location.longitude
#                form.cleaned_data['ponto'] = f"POINT({location.longitude} {location.latitude})"
                form.cleaned_data['ponto'] = GEOSGeometry(f'POINT({location.longitude} {location.latitude}, srid=4326)')
        elif form.cleaned_data.get('foto'):
            photo = form.cleaned_data['foto']
            tags = exifread.process_file(photo.file)
            if 'GPS GPSLatitude' in tags and 'GPS GPSLongitude' in tags:
                latitude_ref = str(tags['GPS GPSLatitudeRef'])
                latitude = str(tags['GPS GPSLatitude'])
                longitude_ref = str(tags['GPS GPSLongitudeRef'])
                longitude = str(tags['GPS GPSLongitude'])
                latitude = eval(latitude.replace(" ", ","))
                longitude = eval(longitude.replace(" ", ","))
                latitude = latitude[0] + latitude[1] / 60 + latitude[2] / 3600
                longitude = longitude[0] + longitude[1] / 60 + longitude[2] / 3600
                if latitude_ref == 'S':
                    latitude = -latitude
                if longitude_ref == 'W':
                    longitude = -longitude
                form.cleaned_data['latitude'] = latitude
                form.cleaned_data['longitude'] = longitude
#                form.cleaned_data['ponto'] = f"POINT({longitude} {latitude})"
                form.cleaned_data['ponto'] = GEOSGeometry(f'POINT({location.longitude} {location.latitude}, srid=4326')

        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy(
            'WebGis:registro_servico_detail', 
            kwargs={'pk': self.object.pk})
 
class RegistroServicoUpdateView(LoginRequiredMixin, UpdateView):
    model = RegistroServico
    form_class = RegistroServicoForm
    template_name = 'WebGis/registro_servico_form_new.html'
    success_url = reverse_lazy('WebGis:registro_servico_list')
    
    def get_success_url(self):
        return reverse_lazy('registro_servico_detail', kwargs={'id': self.id})            

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.instance.ip_origem = self.request.META.get('REMOTE_ADDR')
        if form.cleaned_data.get('endereco'):
            geolocator = Nominatim(user_agent="my-app")
            location = geolocator.geocode(form.cleaned_data['endereco'])
            if location:
                form.cleaned_data['latitude'] = location.latitude
                form.cleaned_data['longitude'] = location.longitude
                #form.cleaned_data['ponto'] = f"POINT({location.longitude} {location.latitude})"
                form.cleaned_data['ponto'] = GEOSGeometry(f"POINT({location.longitude} {location.latitude})")
        elif form.cleaned_data.get('foto'):
            photo = form.cleaned_data['foto']
            tags = exifread.process_file(photo.file)
            if 'GPS GPSLatitude' in tags and 'GPS GPSLongitude' in tags:
                latitude_ref = str(tags['GPS GPSLatitudeRef'])
                latitude = str(tags['GPS GPSLatitude'])
                longitude_ref = str(tags['GPS GPSLongitudeRef'])
                longitude = str(tags['GPS GPSLongitude'])
                latitude = eval(latitude.replace(" ", ","))
                longitude = eval(longitude.replace(" ", ","))
                latitude = latitude[0] + latitude[1] / 60 + latitude[2] / 3600
                longitude = longitude[0] + longitude[1] / 60 + longitude[2] / 3600
                if latitude_ref == 'S':
                    latitude = -latitude
                if longitude_ref == 'W':
                    longitude = -longitude
                form.cleaned_data['latitude'] = latitude
                form.cleaned_data['longitude'] = longitude
                form.cleaned_data['ponto'] = GEOSGeometry(f"POINT({location.longitude} {location.latitude})")
                #form.cleaned_data['ponto'] = f"POINT({longitude} {latitude})"

        return super().form_valid(form)
    def get_success_url(self):
            return reverse_lazy('registro_servico_detail', kwargs={'pk': self.object.pk})

class RegistroServicoDeleteView(LoginRequiredMixin, DeleteView):
    model = RegistroServico
    template_name = 'WebGis/registro_servico_confirm_delete.html'
    success_url = reverse_lazy('WebGis:registro_servico_list')
    
class RegistroServicoListView(ListView):
    model = RegistroServico
    paginate_by = 10
    template_name = 'WebGis/registro_servico_list.html'
    context_object_name = 'registro_servicos'

class RegistroServicoDetailView(LoginRequiredMixin, DetailView):
    model = RegistroServico
    template_name = 'WebGis/registro_servico_detail.html'
    context_object_name = 'registro_servicos'
    success_url = reverse_lazy('WebGis:registro_servico_list')

WebGis_Projeto/WebGis/templates/WebGis/base.html
<!DOCTYPE html>
<html>
    <title>ReporteUFPR</title>
    {% load static %}
    <!-- Adicionando os arquivos CSS do Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Adicionando o arquivo CSS personalizado -->
    <link rel="stylesheet" href="{% static 'WebGis/css/style.css' %}">
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />     
    <!-- Include Moment.js CDN -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<body>
  <!-- Barra de menu no topo -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'WebGis:index'%}">
            <img src="/fotos/fotos/mulher_preta.png" 
            width="40" 
            height="30" 
            class="d-inline-block align-top" 
            alt="">
            ReporteUFPR
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
               <a class="nav-link" href="{% url 'WebGis:index'%}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" disabled href="{% url 'WebGis:index'%}">Sobre</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" 
                    href="{% url 'WebGis:servico_list'%}" 
                    role="button" 
                    data-toggle="dropdown" 
                    aria-expanded="false">
                    Serviços
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'WebGis:servico_create'%}">Cadastrar</a>
                    <a class="dropdown-item" href="{% url 'WebGis:servico_list'%}">Listar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'WebGis:servico_list'%}">Excluir</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                    href="{% url 'WebGis:categoria_list'%}"
                    role="button" 
                    data-toggle="dropdown" 
                    aria-expanded="false"
                    >Categorias
                </a>
                <div class="dropdown-menu">

                    <a class="dropdown-item" href="{% url 'WebGis:categoria_list'%}">Listar</a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %} 
                        <a class="dropdown-item" href="{% url 'WebGis:categoria_create'%}">Cadastrar</a>
                        <a class="dropdown-item" href="{% url 'WebGis:categoria_list'%}">Excluir</a>
                    {% endif %}

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" 
                    href="{% url 'WebGis:registro_servico_list'%}"
                    role="button" 
                    data-toggle="dropdown" 
                    aria-expanded="false">
                    Ocorrências
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'WebGis:registro_servico_list'%}">Listar</a>                    
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'WebGis:registro_servico_create'%}">Cadastrar</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'WebGis:registro_servico_list'%}">Excluir</a>
                    {% endif %}
                    </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" 
                    href="{% url 'WebGis:registro_servico_list'%}"
                    role="button" 
                    data-toggle="dropdown" 
                    aria-expanded="false">
                    Campus
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Listar</a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="#">Cadastrar</a>
                        <a class="dropdown-item" href="#">Excluir</a>
                    {% endif %}
                </div>
            </li>
            <li class="nav-item active">
                {% if user.is_authenticated %}
                    <p> {{ user.email }} </p>
                {% else %}
                    <a class="nav-link" href="{% url 'WebGis:index'%}">
                        Login
                    </a>
                {% endif %}

             </li> 
        </ul>
        </div>
    </div>
</nav>
<!-- Imagem no topo -->
<header class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-6">ReporteUFPR - Sistema de Colaboração Voluntária</h1>
        <p class="lead">Bem-vind(oa)!!! Colabore com a Comunidade Universitária <p>
        <p class="lead">Informando problemas e dificuldades encontradas no seu dia a dia na UFPR!</p>
    </div>
</header>

{% block content%}
{% endblock content%}
{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}

<!-- Adicionando os arquivos JS do Bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
</body>
</html>

WebGis_Projeto/WebGis/templates/WebGis/categoria_confirm_delete.html
<!-- meu_app/categoria_confirm_delete.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Confirmar exclusão da Categoria</title>
</head>
<body>
    <h1>Confirmar exclusão da Categoria</h1>
    <p>Você está prestes a excluir a categoria "{{ categoria.nome }}". Tem certeza de que deseja continuar?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Excluir">
    </form>
</body>
</html>

WebGis_Projeto/WebGis/templates/WebGis/categoria_form.html
<!-- meu_app/categoria_form.html -->
{% extends 'WebGis/base.html' %}

{% load static%}
{% load crispy_forms_tags %}

{% block content %}

<h3>Formulário de Categoria</h3>

<p class="lead">Preencha todos os campos obrigatórios</p>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Salvar">
</form>

{% endblock content%}

WebGis_Projeto/WebGis/templates/WebGis/categoria_list.html
<!-- templates/meu_app/servico_list.html -->
{% extends 'WebGis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
    <title>Lista das Categorias</title>
</head>
<body>
{% block content %}
    <h1>Lista das Categorias Disponíveis</h1>
    <ul>
        {% for categoria in categorias %}
            <li>{{ categoria }}</li>
        {% empty %}
            <li>Nenhum serviço encontrado.</li>
        {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>

WebGis_Projeto/WebGis/templates/WebGis/index.html
<!DOCTYPE html>
{% extends 'WebGis/base.html' %}

{% block content %}
<!-- Script para inicializar o mapa e capturar a latitude e longitude -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var map = L.map('map').setView([-25.45246 , -49.23398], 14);
      //var map = L.map('map').locate({setView: true}, 16);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);
//      var marker = L.marker([-25.45246 , -49.23398], { draggable: true }).addTo(map);
//      var popup = L.popup().setContent("Esta é sua Localização <br> Atual e Aproximada!!!");
      var popup = L.popup().setContent("Esta é sua Localização <br> Atual e Aproximada!!!");
      var marker = L.marker([-25.45246 , -49.23398], {draggable: true}).addTo(map);
      function getLocation() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var latitude = position.coords.latitude;
              var longitude = position.coords.longitude;
              if(marker){
                map.removeLayer(marker);
                document.getElementById('latitude').value = "latitude";
                document.getElementById('latitude').value = "longitude";      
              }
              if(popup){
                map.removeLayer(popup);
              };
              marker.setLatLng([latitude, longitude]);
              document.getElementById('latitude').value = "latitude";
              document.getElementById('latitude').value = "longitude";      
              marker.addTo(map);
              popup.setLatLng([latitude, longitude]);
              popup.setContent("Esta é sua Localização <br> Atual e Aproximada!!!")
              marker.bindPopup(popup).openPopup();
              popup.openOn(map);
            });
          } else {
            alert('Geolocalização não é suportada pelo seu navegador.');        }
      }
    });

  </script>

  <!-- Mapa -->
  <section id="map">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div id="map" style="height: 480px; width: 600px;"></div>
        </div>
      </div>
    </div>
  </section>
<section id="botao">
  <div class="container align=center">
    <a class="btn btn-primary" href="{% url 'WebGis:registro_servico_create'%}" role="button"> Clique aqui para Registrar uma Ocorrência!!!</a>
  </div>
</section>
  {% endblock content %}

WebGis_Projeto/WebGis/templates/WebGis/registro_servico_confirm_delete.html
<!-- meu_app/registro_servico_confirm_delete.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Confirmar exclusão do Registro de Serviço</title>
</head>
<body>
    <h1>Confirmar exclusão do Registro de Serviço</h1>
    <p>Você está prestes a excluir o registro de serviço "{{ registro_servico }}". Tem certeza de que deseja continuar?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Excluir">
    </form>
</body>
</html>

WebGis_Projeto/WebGis/templates/WebGis/registro_servico_detail.html
<!-- meu_app/registro_servico_detail.html -->
{% extends 'WebGis/base.html' %}

{% block  content %}
    <h1>Detalhes do Registro de Serviço</h1>
    <p>ID: {{ registro_servicos.id }}</p>
    <p><b>Serviço: </b>{{ registro_servicos.servico }}</p>
    <p><b>Usuário: </b> {{ registro_servicos.usuario }}</p>
    <p>IP de Registro: {{ registro_servicos.ip_origem }}</p>
    <p>Data de Registro: {{ registro_servicos.data_registro }}</p>
    <p>Data de Alteração: {{ registro_servicos.data_alteracao }}</p>
    <p>Ponto: {{ registro_servicos.ponto }}</p>
    <p>Endereço: {{ registro_servicos.endereco }}</p>
    {% if registro_servicos.foto %}
        <p><figure class="image-preview"> 
            <img src={{ registro_servicos.foto.url }} 
            class="figure-img img-fluid rounded" 
            alt={{ "registro_servicos.servico" }}>
            <figcaption class="figure-caption">
                {{ registro_servicos.foto.url }} 
            </figcaption>
            </figure>
        </p>
        <p>
            Foto:
            <a href= {{ registro_servicos.foto.url}}>
            {{ registro_servicos.servico}}
            </a>
        </p>
    {% else%}
        <p>Foto Não Disponível</p>
    {% endif %}

{% endblock content %}

WebGis_Projeto/WebGis/templates/WebGis/registro_servico_list.html
{% extends 'WebGis/base.html' %}

{% block content %}

    <h1>Lista de Registros de Serviço</h1>
    <ul>
        <table class="table table-striped">
            <thead class="thead-dark"> Registros de Serviços</thead>
            <th scope="col">ID</th>
            <th scope="col">Serviço Demandado</th>
            <th scope="col">Data do Registro</th>
            <th scope="col">Data da Ocorrência</th>
            <th scope="col">IP do Usuário</th>
            <th scope="col">Foto</th>
        </thead>
        <tbody>

        {% for registro_servico in registro_servicos %}
        <tr>
            <td><a href="{% url 'WebGis:registro_servico_detail' registro_servico.id %}">{{ registro_servico.id }}</a></td>
            <td>{{ registro_servico.servico }}</td>
            <td>{{ registro_servico.data_registro }}</td>
            <td>{{ registro_servico.data_alteracao }}</td>
            <td>{{ registro_servico.ip_origem }}</td>
            {% if registro_servico.foto %}
                <td>
                    <a href= {{ registro_servico.foto.url}}>
                        {{ registro_servico.servico}}
                    </a>
                </td>
            {% else%}
                <td>Foto Não Disponível</td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </ul>
{% endblock content %}

WebGis_Projeto/WebGis/templates/WebGis/servico_confirm_delete.html
<!-- meu_app/servico_confirm_delete.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Confirmar exclusão do Serviço</title>
</head>
<body>
    <h1>Confirmar exclusão do Serviço</h1>
    <p>Você está prestes a excluir o serviço "{{ servico.nome }}". Tem certeza de que deseja continuar?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Excluir">
    </form>
</body>
</html>